# Default values for deploys.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

shared:
  defaultDomains: 
    - reclique-rancher.daxko.tech
    - recliquecore.com
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    repo: kong/httpbin


prd_deploy_two_alpha:
  environment: prd
  application: deploy-two
  image:
    version: '0.1.0'
  customers:
    - name: ccptest
      vanityDomains:
        - ccptest.tmiller.dev
    - name: cookies


prd_deploy_two:
  environment: prd
  application: deploy-two
  image:
    version: '0.1.0'
  customers:
    - name: google


prd_deploy_one_alpha:
  environment: prd
  application: deploy-one
  image:
    version: '0.1.0'
  customers:
    - name: apple


prd_deploy_one:
  environment: prd
  application: deploy-one
  image:
    version: '0.1.0'
  customers:
    - name: android


stg_deploy_two:
  environment: stg
  application: deploy-two
  image:
    version: latest
  customers:
    - name: target


stg_deploy_one:
  environment: stg
  application: deploy-one
  image:
    version: latest
  customers:
    - name: aldi
