# Default values for deploys.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

stg:
  core:
    environment: stg
    application: core
    helm:
      gitRepository: https://github.com/tmiller/helm-httpbin.git
      gitRevision: main
    image:
      version: latest
      repo: kong/httpbin
    customers:
      - applebees

  legacy:
    environment: stg
    application: legacy
    helm:
      gitRepository: https://github.com/tmiller/helm-httpbin.git
      gitRevision: main
    image:
      version: latest
      repo: kong/httpbin
    customers:
      - longjohns

prd:
  core:
    alpha:
      environment: prd
      application: core
      helm:
        gitRepository: https://github.com/tmiller/helm-httpbin.git
        gitRevision: main
      image:
        version: 0.1.0
        repo: kong/httpbin
      customers:
        - apple
    rest:
      environment: prd
      application: core
      helm:
        gitRepository: https://github.com/tmiller/helm-httpbin.git
        gitRevision: main
      image:
        version: 0.1.0
        repo: kong/httpbin
      customers:
        - google
        - microsoft

  legacy:
    alpha:
      environment: prd
      application: legacy
      helm:
        gitRepository: https://github.com/tmiller/helm-httpbin.git
        gitRevision: main
      image:
        version: 0.1.0
        repo: kong/httpbin
      customers: []
    rest:
      environment: prd
      application: legacy
      helm:
        gitRepository: https://github.com/tmiller/helm-httpbin.git
        gitRevision: main
      image:
        version: 0.1.0
        repo: kong/httpbin
      customers:
        - daxko
        - region
        - alabama-power
