# Default values for deploys.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

customerVersion: 1.0.0

stg:
  core:
    environment: stg
    application: core
    helm:
      gitRepository: https://github.com/tmiller/helm-httpbin.git
      gitRevision: main
    image:
      version: latest
      repo: kong/httpbin
    customers:
      - applebees

  legacy:
    environment: stg
    application: legacy
    helm:
      gitRepository: https://github.com/tmiller/helm-httpbin.git
      gitRevision: main
    image:
      version: latest
      repo: kong/httpbin
    customers:
      - longjohns
