# Default values for deploys.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


stg_deploy_two:
  environment: stg
  application: deploy-two
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: latest
    repo: kong/httpbin

  customers:
    - name: ccptest


stg_deploy_one:
  environment: stg
  application: deploy-one
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: latest
    repo: kong/httpbin

  customers: []


prd_deploy_two_alpha:
  environment: prd
  application: deploy-two
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: '0.1.0'
    repo: kong/httpbin

  customers: []


prd_deploy_two_rest:
  environment: prd
  application: deploy-two
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: '0.1.0'
    repo: kong/httpbin

  customers: []


prd_deploy_one_alpha:
  environment: prd
  application: deploy-one
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: '0.1.0'
    repo: kong/httpbin
  customers: []


prd_deploy_one_rest:
  environment: prd
  application: deploy-one
  rootDomain: reclique-rancher.daxko.tech
  helm:
    gitRepository: https://github.com/tmiller/helm-httpbin.git
    gitRevision: main
  image:
    version: '0.1.0'
    repo: kong/httpbin
  customers: []
