apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-50'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: System services
  sourceRepos:
    - '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - developers
