apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  project: default
  source:
    repoURL: https://github.com/tmiller/helm-applications
    targetRevision: main
    path: .
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true

{{ include "application" (mergeOverwrite .Values.shared .Values.prd_deploy_two_alpha) }}
{{ include "application" (mergeOverwrite .Values.shared .Values.prd_deploy_two) }}

{{ include "application" (mergeOverwrite .Values.shared .Values.prd_deploy_one_alpha) }}
{{ include "application" (mergeOverwrite .Values.shared .Values.prd_deploy_one) }}

{{ include "application" (mergeOverwrite .Values.shared .Values.stg_deploy_two) }}
{{ include "application" (mergeOverwrite .Values.shared .Values.stg_deploy_one) }}
