apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reclique-deployments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    rgocd.argoproj.io/sync-wave: "-50"
spec:
  project: default
  source:
    repoURL: https://github.com/tmiller/helm-applications
    targetRevision: {{ .Values.customerVersion }}
    path: .
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
